server:
  port: 8082
spring:
    cloud:
      sentinel:
        transport:
          port: 8719
          dashboard: 127.0.0.1:8080
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848  #Nacos服务器侦听器的IP和端口
          weight:  10 # 值范围：1到100。值越大,权重越大