server:
  port: 8082
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
    nacos:
      discovery:
        server-addr: localhost:8848  #Nacos服务器侦听器的IP和端口 #80不能省略
        weight:  10 # 值范围：1到100。值越大,权重越大
    alibaba:
      seata:
        tx-service-group: tx-service-group
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3307/seata?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true
    username: root
    password:  123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  rocketmq:
    name-server-address: localhost:9876
    # 可选, 如果无需发送消息则忽略该配置
    producer-group: ${spring.application.name}-producer
    # 发送超时配置毫秒数, 可选, 默认3000
    send-msg-timeout: 5000
    # 追溯消息具体消费情况的开关，默认打开
    #trace-enabled: false
    # 是否启用VIP通道，默认打开
    #vip-channel-enabled: false
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848  #80不能省略
  scan:
    base-packages: com.lc.cloud.alibaba.provider.dubbo
  cloud:
    subscribed-services: nacos-consumer