server:
  port: 8082
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: nacos.ayouran.com:80  #Nacos服务器侦听器的IP和端口
        weight:  10 # 值范围：1到100。值越大,权重越大
  main.allow-bean-definition-overriding: true
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: com.lc.cloud.alibaba.provider.service.impl