rocketmq:
  container_name: rocketmq
  build: docker
  restart: always
  ports:
    - "10911:10911"
    - "9876:9876"
  environment:
    TZ: "Asia/Shanghai"
    JAVA_HOME: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
    JRE_HOME: "${JAVA_HOME}/jre"
    CLASSPATH: ".:${JAVA_HOME}/lib:${JRE_HOME}/lib"
    PATH: "${JAVA_HOME}/bin:$PATH"