server:
  port: 8081
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
    nacos:
      discovery:
        server-addr: localhost:8848  #Nacos服务器侦听器的IP和端口 #80不能省略
        weight:  10 # 值范围：1到100。值越大,权重越大
  main.allow-bean-definition-overriding: true
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848  #80不能省略
  consumer:
    check: false   #不检查dubbo服务依赖